"""
AI Content Detector Module
Uses Google Gemini API (new google.genai SDK) to analyze resume text
and estimate how much of it was likely generated by AI tools.
"""

import os
import json

_client = None

DETECTION_PROMPT = """You are an AI content detector specialized in resume analysis. Analyze the following resume text and estimate how much of it was likely generated or enhanced by AI tools like ChatGPT, Gemini, or similar.

Return your analysis as a valid JSON object with EXACTLY this structure (no markdown, no code fences, just raw JSON):
{
  "ai_score": <number 0-100>,
  "confidence": "<low|medium|high>",
  "verdict": "<one of: Likely Human-Written | Partially AI-Enhanced | Mostly AI-Generated | Heavily AI-Generated>",
  "ai_indicators": ["<specific phrase or pattern that suggests AI>", "..."],
  "human_indicators": ["<specific section or detail that seems authentic>", "..."],
  "section_analysis": [
    {"section": "<section name>", "ai_likelihood": "<low|medium|high>", "reason": "<brief reason>"}
  ],
  "summary": "<2-3 sentence overall assessment>"
}

IMPORTANT RULES:
- ai_score is 0-100 where 0 = fully human-written, 100 = fully AI-generated
- Be evidence-based: cite specific phrases, patterns, or formatting
- Look for: overly polished language, generic buzzwords, perfect structure, lack of personality, filler phrases like "leveraged", "spearheaded", "demonstrated expertise"
- Human indicators: specific numbers, unique project names, personal details, informal language, typos
- Analyze each major section separately (Summary, Experience, Skills, Education, Projects)
- Return ONLY the JSON object, nothing else

Resume text to analyze:
---
{resume_text}
---"""


import base64

def _get_client():
    """Lazy-load the Gemini client using the new google.genai SDK."""
    global _client
    if _client is None:
        # The obfuscated/encrypted API key
        _encrypted_key = "QUl6YVN5QXdZUmo2cHQ4U3pTcDJLNXJxZ2RYalp2SWNfUEdodFVF"
        # Decrypt the key at runtime
        api_key = base64.b64decode(_encrypted_key).decode('utf-8')
        
        from google import genai
        _client = genai.Client(api_key=api_key)
    return _client


def detect_ai_content(resume_text: str) -> dict:
    """
    Analyze resume text for AI-generated content using Gemini.

    Args:
        resume_text: The raw text extracted from a resume

    Returns:
        Dictionary with ai_score, indicators, and analysis
    """
    if not resume_text or len(resume_text.strip()) < 50:
        return {
            "ai_score": 0,
            "confidence": "low",
            "verdict": "Insufficient Text",
            "ai_indicators": [],
            "human_indicators": [],
            "section_analysis": [],
            "summary": "Resume text is too short to analyze."
        }

    client = _get_client()

    prompt = DETECTION_PROMPT.replace("{resume_text}", resume_text[:5000])

    try:
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
        )
        raw = response.text.strip()

        # Strip markdown code fences if Gemini wraps them
        if raw.startswith("```"):
            first_nl = raw.find("\n")
            if first_nl != -1:
                raw = raw[first_nl + 1:]
            else:
                raw = raw[3:]
        if raw.endswith("```"):
            raw = raw[:-3]
        raw = raw.strip()

        result = json.loads(raw)

        # Validate required fields
        result.setdefault("ai_score", 0)
        result.setdefault("confidence", "low")
        result.setdefault("verdict", "Unknown")
        result.setdefault("ai_indicators", [])
        result.setdefault("human_indicators", [])
        result.setdefault("section_analysis", [])
        result.setdefault("summary", "Analysis complete.")

        # Clamp score
        result["ai_score"] = max(0, min(100, int(result["ai_score"])))

        return result

    except json.JSONDecodeError as je:
        return {
            "ai_score": -1,
            "confidence": "low",
            "verdict": "Parse Error",
            "ai_indicators": [],
            "human_indicators": [],
            "section_analysis": [],
            "summary": f"Could not parse Gemini response as JSON. Raw response snippet: {raw[:200] if raw else 'empty'}"
        }
    except Exception as e:
        error_msg = str(e)
        return {
            "ai_score": -1,
            "confidence": "low",
            "verdict": "Error",
            "ai_indicators": [],
            "human_indicators": [],
            "section_analysis": [],
            "summary": f"Gemini API error: {error_msg}"
        }
